POST http://localhost:3003/api/blogs
Content-Type: application/json

{
"title": "Uusi blogi", "author": "Testaaja", "url": "https://fullstackopen.com/osa4/sovelluksen_rakenne_ja_testauksen_alkeet", "likes": "3"
}